= Congratulations!
:showtitle:
:page-title: Jekyll AsciiDoc Quickstart
:page-description: A forkable blog-ready Jekyll site using AsciiDoc

You've successfully set up and deployed an Jekyll website powered by AsciiDoc using the 
https://github.com/asciidoctor/jekyll-asciidoc-quickstart[*Jekyll AsciiDoc Quickstart*] project. 
If everything is in order then changes to the AsciiDoc content will be automatically published to your `gh_pages` branch and hosted via Jekyll and Github.

== What do I do now?

Now that you've set up your website to run with AsciiDoc, you have a ton of options available to you.

=== Edit content

Editing content is very simple. The easiest way to update your site is to clone your repository, 
fire up your favorite text editor and run the content locally. 
To do this run the `jekyll serve` command and open a web browser to http://localhost:4000. 
Jekyll will automatically process and host changes to the content. 
Also make sure that your `Gemfile` is up-to-date with the current version of your gem sources, 
e.g. with `gem list --local | grep "jekyll"`.

You may also edit your content directly on Github. 
To do this, navigate the browser the file you wish to edit, click the pensil (edit) button in 
the upper right hand corner of the view and make your changes. When you're finished, commit your changes. 
This will trigger Travis to generate and publish a new website including your changes.

=== Reference documentation

The following links will help with detailed explanations on Jekyll and AsciiDoc.

* http://jekyllrb.com[Jekyll]
* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference]
* http://asciidoctor.org[Asciidoctor]
